name: Blog and Douban

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: sun0225SUN/Social-Readme@main
        with:
          blog_rss_link: https://blog.sunguoqi.com/rss.xml
          douban_name: sun0225SUN
          blog_limit: 5 # blog数量
          douban_limit: 5 # 豆瓣最新动态数量
          commit_message: Updated social rss by social-readme # commit说明
