name: Latest Blog Post

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: sun0225SUN/Latest-Blog-Post@main
        with:
          blog_rss_link: https://blog.sunguoqi.com/rss.xml
          blog_limit: 5 # blog数量
